json_schema:
    path:     /json/{depth}/{class}
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:json", class : 0, depth: 0 }

graph_schema:
    path:     /graph/{depth}/{class}
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:graph", class : 0, depth: 0 }

list_schema:
    path:     /
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:list" }
