all_schema:
    path:     /all
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:all" }

all_graph_schema:
    path:     /graph
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:allGraph" }

list_schema:
    path:     /
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:list" }

single_schema:
    path:     /single/{class}
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:single" }

single_graph_schema:
    path:     /graph/{class}
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:singleGraph" }
