all_schema:
    path:     /all
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:all" }

graph_schema:
    path:     /graph
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:graph" }

list_schema:
    path:     /
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:list" }

single_schema:
    path:     /single/{class}
    defaults: { _controller: "LthrtSchemaVisualizerBundle:Schema:single" }

